[package]
name = "project_euler"
version = "0.0.1"
authors = ["Renato Zannon <renato@rrsz.com.br>"]

[dependencies]
num = "*"
ascii = "*"
enum-set = "*"
itertools = "*"

[dependencies.shared]
path = "lib"

[profile.release]
lto = true
