[package]
name = "project_euler"
version = "0.0.1"
authors = ["Renato Zannon <renato@rrsz.com.br>"]

[dependencies]
ascii = "0.9"
enum-set = "0.0.7"
enum_primitive = "0.1"
itertools = "0.7"
num = "0.2"
shared = { path = "shared" }

[profile.release]
debug = true

[workspace]
members = ["shared"]
