[package]
name = "project_euler"
version = "0.0.1"
authors = ["Renato Zannon <renato@rrsz.com.br>"]

[dependencies]
num = "^0.1.0"
ascii = "*"
collect = "*"

[dependencies.shared]
path = "lib"

[profile.release]
lto = true
