[package]
name = "project_euler"
version = "0.0.1"
authors = ["Renato Zannon <renato@rrsz.com.br>"]

[dependencies]
num = "*"
ascii = "*"

[dependencies.collect]
git = "https://github.com/Gankro/collect-rs"

[dependencies.shared]
path = "lib"

[profile.release]
lto = true
